image: python:latest

pages:
  stage: deploy
  only:
    - master
  script:
    - apt install python3-pip
    - pip install ".[docs]"
    - mkdocs build --site-dir public
  artifacts:
    paths:
    - public

