image: python:latest

pages:
  stage: deploy
  only:
    - master
  script:
    - apk add py3-pip
    - pip install ".[docs]"
    - mkdocs build --site-dir public
  artifacts:
    paths:
    - public

