image: python:latest

pages:
  tags:
    - docker
  stage: deploy
  only:
    - master
    - dev
  script:
    - pip install ".[docs]"
    - mkdocs build --site-dir public
  artifacts:
    paths:
    - public

