image: python:latest

default:
  tags:
    - docker

before_script:
  - pip install ".[docs]"

pytest:
  stage: testing
  only:
    - master
  script:
    - pytest

pages:
  stage: deploy
  only:
    - master
  script:
    - pip install ".[docs]"
    - mkdocs build --site-dir public
  artifacts:
    paths:
    - public

