image: python:latest

pages:
  stage: deploy
  only:
    - master
  script:
    - apt-get update -q -y
    - apt-get install -y python-pip
    - pip install ".[docs]"
    - mkdocs build --site-dir public
  artifacts:
    paths:
    - public

