site_name: Scyan
repo_url: https://github.com/MICS-Lab/scyan
repo_name: MICS-Lab/scyan
copyright: Copyright &copy; 2021 - 2022 Quentin Blampey
theme:
  name: material
  logo: assets/logo_white.svg
  favicon: assets/favicon.png
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Tutorials:
    - tutorials/preprocessing.ipynb
    - tutorials/usage.ipynb
    - tutorials/batch_effect_correction.ipynb
    - tutorials/population_discovery.ipynb
    - tutorials/debarcoding.ipynb
  - API: 
    - scyan.Scyan: api/model.md
    - Modules:
      - scyan.module.ScyanModule: api/module.md
      - scyan.module.PriorDistribution: api/prior.md
      - scyan.module.RealNVP: api/real_nvp.md
      - scyan.module.CouplingLayer: api/coupling_layer.md
      - scyan.module.LossMMD: api/loss_mmd.md
    - Plots: api/plots.md
    - Tools:
      - Preprocessing: api/preprocessing.md
      - Representation: api/representation.md
      - Results analysis: api/analysis.md
    - Loading/adding datasets: api/datasets.md
    - Read/write FCS: api/io.md
  - Advanced usage:
    - Add your own dataset: advanced/data.md
    - Advice to make the knowledge table: advanced/advice.md
    - Selecting parameters: advanced/parameters.md
    - Configuration and monitoring: advanced/hydra_wandb.md
    - CLI/Running scripts: advanced/scripts.md
  - Cite us: cite.md
plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true 

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js