site_name: Scyan
repo_url: https://gitlab-research.centralesupelec.fr/mics_biomathematics/biomaths/scyan
repo_name: biomaths/scyan
copyright: Copyright &copy; 2021 - 2022 Quentin Blampey
theme:
  name: material
  logo: assets/logo_medium.png
  favicon: assets/favicon.png
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Tutorials: tutorials.md
  - API: 
    - scyan.Scyan: api/model.md
    - Modules:
      - scyan.module.ScyanModule: api/module.md
      - scyan.module.PriorDistribution: api/prior.md
      - scyan.module.RealNVP: api/real_nvp.md
      - scyan.module.CouplingLayer: api/coupling_layer.md
    - Plotting tools:
      - scyan.plot.scatter: api/scatter.md
      - scyan.plot.probs_per_marker: api/probs_per_marker.md
      - scyan.plot.latent_heatmap: api/latent_heatmap.md
      - scyan.plot.subclusters: api/subclusters.md
      - scyan.plot.latent_expressions: api/latent_expressions.md
      - scyan.plot.kde_per_population: api/kde_per_population.md
    - IO / Data / Misc:
      - scyan.data.load: api/load.md
      - scyan.utils.read_fcs: api/read_fcs.md
      - scyan.utils.write_fcs: api/write_fcs.md
      - scyan.utils.subcluster: api/subcluster.md
      - scyan.mmd.LossMMD: api/loss_mmd.md
  - Cite us: cite.md
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
