# @package _global_

defaults:
  - override /hydra/sweeper: optuna

optimized_metric: Heuristic

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true

    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    direction: minimize
    storage: null
    n_trials: 40
    n_jobs: 1

    params:
      model.temperature: tag(log, interval(0.5, 10))
      model.modulo_temp: range(2, 4)
      model.hidden_size: choice(16, 32)
      model.n_hidden_layers: range(6, 8)
      model.n_layers: range(6, 8)
      model.prior_std: interval(0.15, 0.35)
      model.lr: tag(log, interval(0.0001, 0.002))
      model.batch_size: choice(4096, 8192, 16384, 32768)
      callbacks.early_stopping.patience: range(2, 5)
      callbacks.early_stopping.min_delta: tag(log, interval(0.25, 2))
