# @package _global_

defaults:
  - override /hydra/sweeper: optuna

optimized_metric: Heuristic

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true

    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    direction: minimize
    storage: null
    n_trials: 50
    n_jobs: 1

    search_space:
      model.temperature:
        type: float
        low: 0.5
        high: 10
        log: true
      model.modulo_temp:
        type: int
        low: 2
        high: 4
      # model.mmd_max_samples:
      #   type: categorical
      #   choices: [512, 1024, 2048]
      # model.alpha_batch_effect:
      #   type: float
      #   low: 10
      #   high: 200
      #   log: true
      model.hidden_size:
        type: categorical
        choices: [16, 32]
      model.n_hidden_layers:
        type: int
        low: 6
        high: 8
      model.n_layers:
        type: int
        low: 6
        high: 8
      model.prior_std:
        type: float
        low: 0.15
        high: 0.35
      model.lr:
        type: float
        low: 0.0001
        high: 0.002
        log: true
      # model.batch_size:
      #   type: categorical
      #   choices: [8192, 16384]
      callbacks.early_stopping.patience:
        type: int
        low: 2
        high: 5
      callbacks.early_stopping.min_delta:
        type: float
        low: 0.25
        high: 2
        log: true
