# @package _global_

defaults:
  - override /hydra/sweeper: optuna

optimized_metric: "silhouette_score"

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true

    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    direction: maximize
    storage: null
    n_trials: 40
    n_jobs: 1

    search_space:
      model.hidden_size:
        type: categorical
        choices: [16, 32, 64, 128, 256]
      model.n_layers:
        type: int
        low: 4
        high: 12
      model.n_hidden_layers:
        type: int
        low: 4
        high: 12
      model.lr:
        type: float
        low: 0.0001
        high: 0.005
        log: true
      model.batch_size:
        type: categorical
        choices: [1024, 4096, 16384, 65536]
