# @package _global_

defaults:
  - override /hydra/sweeper: optuna

optimized_metric: silhouette_score

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true

    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    direction: maximize
    storage: null
    n_trials: 40
    n_jobs: 1

    search_space:
      model.hidden_size:
        type: categorical
        choices: [16, 32]
      model.n_layers:
        type: int
        low: 5
        high: 8
      model.n_hidden_layers:
        type: int
        low: 5
        high: 8
      model.lr:
        type: float
        low: 0.0005
        high: 0.002
        log: true
      model.alpha:
        type: float
        low: 0.5
        high: 2
        log: true
      model.prior_std:
        type: float
        low: 0.1
        high: 0.3
        log: true
      model.ratio_threshold:
        type: float
        low: 0.0005
        high: 0.01
        log: true
