# @package _global_

defaults:
  - override /hydra/sweeper: optuna

optimized_metric: Penalized Silhouette

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true

    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    direction: maximize
    storage: null
    n_trials: 60
    n_jobs: 1

    search_space:
      model.alpha:
        type: float
        low: 5000
        high: 100000
        log: true
      model.temperature_mmd:
        type: float
        low: 1.1
        high: 2.5
        log: true
      model.temp_lr_weights:
        type: float
        low: 5
        high: 15
        log: true
      model.mmd_max_samples:
        type: categorical
        choices: [1024, 2048]
      model.hidden_size:
        type: categorical
        choices: [8, 16, 32]
      model.n_hidden_layers:
        type: int
        low: 6
        high: 8
      model.n_layers:
        type: int
        low: 6
        high: 8
      model.prior_std:
        type: float
        low: 0.1
        high: 0.25
        log: true
      model.lr:
        type: float
        low: 0.0005
        high: 0.002
        log: true
      model.batch_size:
        type: categorical
        choices: [8192, 16384]
      callbacks.early_stopping.patience:
        type: int
        low: 2
        high: 5
      callbacks.early_stopping.min_delta:
        type: float
        low: 0.25
        high: 2
        log: true
