defaults:
  - _self_
  - trainer: default
  - sweeper: optuna
  - project: aml

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

wandb:
  mode: disabled # online, offline, disabled
  save_umap: false
  save_umap_latent_space: false

force_all_populations: false
n_run_testing: 20

model:
  _target_: scyan.model.Scyan

  hidden_size: 16
  n_layers: 7
  n_hidden_layers: 7
  lr: 0.001
  batch_size: 16384
  prior_std: 0.15
  alpha: 1000
  kernel_std: 0.5
  temperature_mmd: 2
  temp_lr_weights: 1.5
  mmd_max_samples: 4096

callbacks:
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: loss_epoch
    patience: 4
    min_delta: 0.5
    check_on_train_epoch_end: True

work_dir: ${hydra:runtime.cwd}

seed: 0
