defaults:
  - _self_
  - trainer: default
  - sweeper: optuna
  - model: scyan
  - callbacks: default

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

wandb:
  project: "scyan"
  mode: "disabled" # online, offline, disabled
  save_marker_pop_matrix: false
  save_umap: true

marker_pop_path: ${oc.env:marker_pop_path}
data_path: ${oc.env:data_path}

work_dir: ${hydra:runtime.cwd}

seed: 0
