defaults:
  - _self_
  - trainer: default
  - sweeper: optuna
  - project: aml

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

wandb:
  mode: disabled # online, offline, disabled
  project_name: aml_testing
  save_umap: false
  save_umap_latent_space: false

model:
  _target_: scyan.model.Scyan

  hidden_size: 16
  n_layers: 7
  n_hidden_layers: 7
  lr: 0.001
  batch_size: 16384
  ratio_threshold: 0.005
  prior_std: 0.15
  alpha: 1

callbacks:
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: loss_epoch
    patience: 4
    min_delta: 0.5
    check_on_train_epoch_end: True

work_dir: ${hydra:runtime.cwd}

seed: 0
