### --- Hydra config file ---
### A usage guide can be found here: https://mics-lab.github.io/scyan/advanced/hydra_wandb/
### The main parameters to update are the commented one, the others can remain as such

defaults:
  - _self_
  - project: aml # name of the yaml file in ./config/project
  - trainer: default
  - sweeper: optuna

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

n_run: 5                # Number or run (if hyperoptimization is run, its the number of run per trial)
save_predictions: false # If true, then saves the predictions in the hydra log directory

wandb:
  mode: disabled   # online, offline, disabled
  save_umap: false # save the umap on Weight & Biases


### --- Model default parameters ---
### You can either modify the parameters directly, or via the command line
### Note that you don't have to update it if you run hyperoptimization

model:
  _target_: scyan.model.Scyan

  hidden_size: 16
  n_layers: 7
  n_hidden_layers: 6
  prior_std: 0.3
  lr: 0.0005
  batch_size: 8192
  temperature: 0.5
  modulo_temp: 2

callbacks:
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: loss_epoch
    patience: 3
    min_delta: 0.5
    check_on_train_epoch_end: True

work_dir: ${hydra:runtime.cwd}/hydra_logs

seed: 0
