defaults:
  - _self_
  - trainer: default
  - sweeper: optuna
  - project: aml # name of the config/project yaml file

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

wandb:
  mode: disabled # online, offline, disabled
  save_umap: false

optimized_metric: Heuristic # Metric for hyperoptimisation. Recommended: Heuristic or iLISI
n_run: 5 # Number or run per trial to stabilise the metrics over one set of hyperparameters
save_predictions: false

model:
  _target_: scyan.model.Scyan

  hidden_size: 16
  n_layers: 7
  n_hidden_layers: 7
  prior_std: 0.3
  lr: 0.001
  batch_size: 16384
  temperature: 1
  modulo_temp: 2

callbacks:
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: loss_epoch
    patience: 3
    min_delta: 0.5
    check_on_train_epoch_end: True

work_dir: ${hydra:runtime.cwd}/hydra_logs

seed: 0
