name: scyan
categorical_covariate_keys:
  - batch
palette:
  Unknown: gray
  B-Cell: C10
  PMN/Mono/Macro: C1
  Dendritic-Cell: C11
  Epcam+: C7
  Tcd4_naive/SCM: C3
  Tcd4_CM: C4
  Tcd4_EF/EM/activ: C5
  Tcd4_reg: C6
  Tcd8_naive/SCM: C9
  Tcd8_CM: C8
  Tcd8_EF/EM/activ: C0
  Tcd8_RM: C2
