name: ci 
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'poetry'
    - run: poetry install -E dev
    - run: poetry run pytest
    - run: poetry run mkdocs gh-deploy --force
